@startuml
!define RECTANGLE class

' 学生と教職員は会員のサブタイプ
RECTANGLE 学生 {
  学生番号
}
RECTANGLE 教職員 {
  職員番号
}
RECTANGLE 会員 {
  会員番号
  氏名
  メールアドレス
}

' 図書関連
RECTANGLE 図書 {
  管理番号
  書名
  著者
  出版社
  ISBN
}
RECTANGLE 書籍
RECTANGLE 雑誌

' 貸出関連
RECTANGLE 貸出情報 {
}
RECTANGLE 貸出日
RECTANGLE 返却日

' 予約関連
RECTANGLE 予約情報 {
}
RECTANGLE 予約日時

' 関係定義
学生 --|> 会員
教職員 --|> 会員

図書 <|-- 書籍
図書 <|-- 雑誌

会員 "1" -- "0..*" 予約情報
予約情報 "1" -- "1" 予約日時

会員 "1" -- "0..*" 貸出情報
図書 "1" -- "0..*" 貸出情報
貸出情報 "1" -- "1" 貸出日
貸出情報 "1" -- "1" 返却日
@enduml
