@startuml Robodogドメインモデル図
skinparam componentStyle rectangle

' Robodog
[利用者] o-- [学生]
[利用者] o-- [教職員]
[利用者] o-- [挨拶]
[利用者] o-- [2つの整数]
[利用者] o-- [足し算の結果]

[学生] <|-- []
[教職員] <|-- []
[挨拶] <|-- [夜の挨拶]
[2つの整数] <|-- [1つ目の整数]
[2つの整数] <|-- [2つ目の整数]

@enduml