@startuml Web訪問者システム-ログインシーケンス図
hide footbox
skinparam boundaryBackgroundColor #D5E8D4
skinparam controlBackgroundColor  #F8CECC
skinparam entityBackgroundColor   #DAE8FC

actor 訪問者 as A
boundary メニュー画面 as B1
boundary ログイン画面 as B2
boundary 訪問者一覧画面 as B3
control 入力検証 as C1
control 認証処理 as C2
entity ユーザー情報 as E

== 基本フロー ==
A -> B1: 「ログイン」を選択
B1 -> B2: ログイン画面を表示

A -> B2: ユーザーID、パスワードを入力・送信
B2 -> C1: 入力内容を検証
activate C1

opt 入力内容に不備あり（代替フロー1）
    C1 -> B2: 「ユーザーID、パスワードは正しく入力してください」表示
    
end

C1 -> C2: 認証処理
deactivate C1
activate C2

C2 -> E: ユーザー情報を照合
activate E
E --> C2: 照合結果
deactivate E

opt 認証失敗（代替フロー2）
    C2 -> B2: ログイン画面を再表示
    C2 -> B2: 「ユーザーIDまたはパスワードが間違っています」表示
end

C2 -> E: ユーザー情報を照合
activate E
E --> C2: 訪問者一覧
deactivate E

C2 -> B3: 訪問者一覧画面を表示
deactivate C2
B3 -> A: 訪問者一覧を表示

@enduml
