@startuml
!theme plain

entity 学生 {
  * 学生番号
}

entity 教職員 {
  * 職員番号
}

entity 会員 {
  * 会員番号
  --
  氏名
  メールアドレス
}

entity 図書 {
  * 管理番号
  --
  書名
  著者
  出版社
  ISBN
}

entity 書籍
entity 雑誌

entity 予約情報 {
  * 予約日時
}

entity 貸出情報 {
  * 貸出日
  * 返却日
}

' --- リレーション ---
学生 ||--|| 会員
教職員 ||--|| 会員

図書 ||--o{ 書籍
図書 ||--o{ 雑誌

会員 ||--o{ 予約情報
図書 ||--o{ 予約情報

会員 ||--o{ 貸出情報
図書 ||--o{ 貸出情報

@enduml
